[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="url" type="org.keycloak.forms.login.freemarker.model.UrlBean" --]
[#-- @ftlvariable name="realm" type="org.keycloak.forms.login.freemarker.model.RealmBean" --]
[#-- @ftlvariable name="locale" type="org.keycloak.theme.beans.LocaleBean" --]
[#-- @ftlvariable name="client" type="org.keycloak.forms.login.freemarker.model.ClientBean" --]
[#-- @ftlvariable name="message" type="org.keycloak.theme.beans.MessageBean" --]
[#-- @ftlvariable name="messagesPerField" type="org.keycloak.theme.beans.MessagesPerFieldBean" --]
[#-- @ftlvariable name="auth" type="org.keycloak.forms.login.freemarker.model.AuthenticationContextBean" --]
[#-- @ftlvariable name="login" type="org.keycloak.forms.login.freemarker.model.LoginBean" --]
[#-- @ftlvariable name="user" type="org.keycloak.forms.login.freemarker.model.ProfileBean" --]
[#-- @ftlvariable name="register" type="org.keycloak.forms.login.freemarker.model.RegisterBean" --]
[#-- @ftlvariable name="totp" type="org.keycloak.forms.login.freemarker.model.TotpBean" --]
[#-- @ftlvariable name="otpLogin" type="org.keycloak.forms.login.freemarker.model.TotpLoginBean" --]
[#-- @ftlvariable name="social" type="org.keycloak.forms.login.freemarker.model.IdentityProviderBean" --]
[#-- @ftlvariable name="properties" type="java.util.Map<String, String>" --]
[#function kcSanitize s][/#function]
[#function msg s...][/#function]